name: label-mutex
description: A GitHub Action that facilitates obtaining, releasing, and representing a lock on a shared resource using PR labels.
branding:
  icon: bookmark
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: Github token to use to perform operations
    required: true
  table:
    description: The name of the table that stores the lock. Required on AWS. Ignored on GCS.
    required: false
    default: label-mutex
  bucket:
    description: The name of the bucket that stores the lock. Turns on GCS support implicitly.
    required: false
  partition:
    description: A name for a logical grouping of locks. Only used on AWS.
    required: false
    default: label
  lock:
    description: The name of the lock.
    required: true
  label:
    description: The name of the label used to facilitate control and represent ownership of the lock.
    required: true
outputs:
  locked:
    description: "'true' if the lock has been claimed. 'false' otherwise."
  unlocked:
    description: "'true' if the lock was confirmed to be free. 'false' otherwise."
  html_url:
    description: URL of the PR holding the lock
runs:
  using: docker
  image: Dockerfile
  # image: 'docker://urcomputeringpal/label-mutex:v0.4.0'
