name: label-mutex
branding:
  icon: bookmark
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: Github token to use to perform operations
    required: true
  label:
    description: The name of the label
    required: true
  lock:
    description: The name of the lock
    required: true
  table:
    description: The name of the table
    required: false
    default: label-mutex
  column:
    description: The name of the column
    required: false
    default: label
outputs:
  locked:
    description: 'true' if the lock was obtained. 'false' otherwise.
runs:
  using: docker
  image: Dockerfile