FROM fsouza/fake-gcs-server:1.47@sha256:0eeaaeba5385c7274e8b11a9ff145569799bf17fdb8ba69226a88ff231ad0b44

CMD [ "-host", "0.0.0.0", "-log-level", "trace", "-external-url", "https://localhost:4443", "-backend", "memory" ]
