FROM fsouza/fake-gcs-server:1.47@sha256:1a5b99d01bac100f84003db8807a3e1cbf5159d6d2acfb31f6f090fa782f386d

CMD [ "-host", "0.0.0.0", "-log-level", "trace", "-external-url", "https://localhost:4443", "-backend", "memory" ]
