name: test
on:
  pull_request:
  merge_group:

env:
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"
  AWS_DEFAULT_REGION: us-east-1
  AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
jobs:
  go-test:
    strategy:
      matrix:
        go-version:
          - stable
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local@sha256:c8702bde709520b90930c20ee430d4123cd731da8e544cc4ccae0e2a78ee4fce
        ports:
          - 8000:8000
    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Create local table
        run: ./hack/create-local-table.sh http://localhost:8000
      - name: Test
        run: go test -v ./...
