name: test
on:
  - push

env:
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"
  AWS_DEFAULT_REGION: us-east-1
  AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
jobs:
  go-test:
    strategy:
      matrix:
        include:
          # renovate: datasource=golang-version
          - go_version: 1.21.1
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create local table
        run: ./hack/create-local-table.sh http://localhost:8000
      - name: Test
        run: go test -v ./...
