name: test
on:
  pull_request:
  merge_group:

env:
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"
  AWS_DEFAULT_REGION: us-east-1
  AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
  GCS_ENDPOINT_URL: https://localhost:4443
  GCS_INSECURE_SKIP_VERIFY: "true"
jobs:
  go-test:
    strategy:
      matrix:
        go-version:
          - stable
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local@sha256:d7ebddeb60fa418bcda218a6c6a402a58441b2a20d54c9cb1d85fd5194341753
        ports:
          - 8000:8000
      fake-gcs-server:
        image: ghcr.io/urcomputeringpal/label-mutex-fake-gcs-server:pr-12@sha256:5fdc1fd0914dfda02fef3e85a5b369cd96041ff6e8a57cc8796d264896fcf5ef
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        ports:
          - 4443:4443

    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Create local table
        run: ./hack/create-local-table.sh http://localhost:8000
        timeout-minutes: 1
      - name: Create local bucket
        run: ./hack/create-local-bucket.sh localhost
        timeout-minutes: 1
      - name: Test
        run: go test -v ./...
