name: test
on:
  pull_request:
  merge_group:

env:
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"
  AWS_DEFAULT_REGION: us-east-1
  AWS_DYNAMODB_ENDPOINT_URL: http://localhost:8000
  GCS_ENDPOINT_URL: https://localhost:4443
jobs:
  go-test:
    strategy:
      matrix:
        go-version:
          - stable
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
      fake-gcs-server:
        image: ghcr.io/urcomputeringpal/label-mutex-fake-gcs-server:pr-12
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        ports:
          - 4443:4443

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create local table
        run: ./hack/create-local-table.sh http://localhost:8000
      - name: Create local bucket
        run: ./hack/create-local-bucket.sh https://localhost:4443
      - name: Test
        run: go test -v ./...
